### ISSUE TITLE
ModelEngine entities reset their walk animation when its target moves

### ISSUE THREAD

**Issue by Cestis** [Bloom-host/Petal#2]
Entities modelled by ModelEngine keep cancelling their movement animation when its target location changes. When the target stands still the animation progresses just fine. On purpur works as intended.

Steps to reproduce: 

1. run petal blank server without any plugins
2. install [model engine plugin](https://github.com/Ticxo/Model-Engine-Wiki/blob/master/demo/Model-Engine-Demo-R2.5.2.jar)
3. download [this sample model](https://drive.google.com/file/d/1ty_fSYqzmoVOjLgFxP8DLsRJzb0jisq6/view?usp=sharing) and place it in plugins/ModelEngine/blueprints
4. type command /meg summon luffy silverfish
5. watch its movement reset whenever player moves
6. repeat for purpur and watch it not
7. for better experience, install resource pack generated in the plugin folder (not required)

Petal version: 1.19-pre-2
Purpur version: 1.19-1715 & 1.19-1716
Plugins: only ModelEngine Demo required

Video comparison. Focus on the legs. The moment I stop moving the animation starts to play out correctly.
Petal-1.19-pre-2

https://user-images.githubusercontent.com/3482915/179472194-8b56dfb7-fcf5-43da-bfa1-43ad381f2375.mp4

Purpur-1.19-1715 & Purpur-1.19-1716

https://user-images.githubusercontent.com/3482915/179471698-614e0ade-1045-44ea-a57c-6741f2b3e39a.mov

Additional info:
Purpur 1716 contains some of the petal patches and doesn't have this issue. I think that should narrow the list of possible causes?

Thanks!

Update: looks like the latest purpur build does not have petal patches thus this bug didn't happen on 1716 build.

**Comment by kev626** [comment]
Fixed in pufferfish-gg/Pufferfish@29056e1, in theory

**Comment by Cestis** [comment]
Thanks!
Just tested with build #17 https://ci.pufferfish.host/job/Pufferfish-1.19/17/
and unfortunately the issue still persists.

**Comment by peaches94** [comment]
thanks for creating a issue! ill take a look at me soon

**Comment by konradpomocny** [comment]
can confirm issue still exists on 1.19-pre-3

**Comment by Cestis** [comment]
Can confirm the issue is still there on 1.19-pre-3

**Comment by Cestis** [comment]
Looks like either MEG 3.0.1 or Petal 1.19.2-pre-7 fixed it, so I'm closing it.
